from enum import Enum


class ServerEvent(str, Enum):
    PLAYER_JOINED = "PLAYER_JOINED"
    PLAYER_LEFT = "PLAYER_LEFT"
    TURN_START = "TURN_START"
    PLAYER_ACTION = "PLAYER_ACTION"
    NARRATIVE_EVENT = "NARRATIVE_EVENT"
    STATE_UPDATE = "STATE_UPDATE"
    CHAT = "CHAT"
    ERROR = "ERROR"


class ClientEvent(str, Enum):
    ACTION_MOVE = "ACTION_MOVE"
    ACTION_CHOICE = "ACTION_CHOICE"
    ACTION_COMBAT = "ACTION_COMBAT"
    ACTION_END_TURN = "ACTION_END_TURN"
    CHAT = "CHAT"
